name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update agda
      run: |
        sudo sed -i 's/jammy/kinetic/' /etc/apt/sources.list
        sudo apt-get -y update
    - name: Install packages
      run: sudo apt-get -y install agda
    - name: Download cubical library
      run: |
        git clone https://github.com/agda/cubical.git
        mkdir ~/.agda
        echo "cubical" > ~/.agda/defaults
        echo "`pwd`/cubical/cubical.agda-lib" > ~/.agda/libraries
    - name: Build Agda
      run: make
    - name: Build doc
      run: make -C agda html
    - name: Deploy doc
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        branch: gh-pages
        folder: agda/html
